### ISSUE TITLE
A  non-numeric value encountered in file: poller_hmib.php  on line:  748

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_hmib#12]
```>2019/02/20  12:37:33 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/hmib/poller_hmib.php[148]:checkHost(),  /plugins/hmib/poller_hmib.php[548]:collect_hrProcessor(),  /plugins/hmib/poller_hmib.php[919]:collectHostIndexedOid(),  /plugins/hmib/poller_hmib.php[748]:CactiErrorHandler())
--
2019/02/20 12:37:33 - ERROR PHP WARNING in  Plugin 'hmib': A  non-numeric value encountered in file:  /var/www/localhost/htdocs/cacti/plugins/hmib/poller_hmib.php  on line:  748
```

**Comment by jdcoats** [comment]
Still exists
```
2019/03/05 10:51:25 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/hmib/poller_hmib.php[148]:checkHost(),  /plugins/hmib/poller_hmib.php[548]:collect_hrProcessor(),  /plugins/hmib/poller_hmib.php[919]:collectHostIndexedOid(),  /plugins/hmib/poller_hmib.php[748]:CactiErrorHandler())
2019/03/05 10:51:25 - ERROR PHP WARNING in  Plugin 'hmib': A  non-numeric value encountered in file:  /var/www/localhost/htdocs/cacti/plugins/hmib/poller_hmib.php  on line:  748
2019/03/05 10:51:25 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/hmib/poller_hmib.php[148]:checkHost(),  /plugins/hmib/poller_hmib.php[548]:collect_hrProcessor(),  /plugins/hmib/poller_hmib.php[919]:collectHostIndexedOid(),  /plugins/hmib/poller_hmib.php[748]:CactiErrorHandler())
2019/03/05 10:51:25 - ERROR PHP WARNING in  Plugin 'hmib': A  non-numeric value encountered in file:  /var/www/localhost/htdocs/cacti/plugins/hmib/poller_hmib.php  on line:  748
```

**Comment by cigamit** [comment]
Should be resolved.

**Comment by jdcoats** [comment]
```

2019/03/08 08:21:11 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'hmib'
--
2019/03/08 08:21:11 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2019/03/08 08:21:11 - ERROR PHP ERROR in  Plugin 'hmib': Uncaught  Error: Function name must be a string in  /var/www/localhost/htdocs/cacti/plugins/hmib/poller_hmib.php:748 Stack  trace: #0  /var/www/localhost/htdocs/cacti/plugins/hmib/poller_hmib.php(924):  collectHostIndexedOid(Array, Array, 'plugin_hmib_hrP...', 'hrProcessor')  #1 /var/www/localhost/htdocs/cacti/plugins/hmib/poller_hmib.php(548):  collect_hrProcessor(Array) #2  /var/www/localhost/htdocs/cacti/plugins/hmib/poller_hmib.php(148):  checkHost('181') #3 {main} thrown in file:  /var/www/localhost/htdocs/cacti/plugins/hmib/poller_hmib.php on line:  748
2019/03/08 08:21:11 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/hmib/poller_hmib.php[148]:checkHost(),  /plugins/hmib/poller_hmib.php[548]:collect_hrProcessor(),  /plugins/hmib/poller_hmib.php[924]:collectHostIndexedOid(),  /plugins/hmib/poller_hmib.php[748]:CactiErrorHandler())
2019/03/08 08:21:11 - ERROR PHP NOTICE in  Plugin 'hmib': Undefined  variable: is_numeric in file:  /var/www/localhost/htdocs/cacti/plugins/hmib/poller_hmib.php  on line:  748

```

**Comment by cigamit** [comment]
Try again.
